'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'

import {
  AnnouncementsCard,
  type DashboardAnnouncement,
} from '@/components/citizen/dashboard/announcements-card'
import {
  RecentComplaintsCard,
  type RecentComplaint,
} from '@/components/citizen/dashboard/recent-complaints-card'
import {
  RecentRequestsCard,
  type RecentRequest,
} from '@/components/citizen/dashboard/recent-requests-card'
import { StatsGrid } from '@/components/citizen/dashboard/stats-grid'
import {
  UnreadRepliesCard,
  type UnreadReply,
} from '@/components/citizen/dashboard/unread-replies-card'
import { VerificationBanner } from '@/components/citizen/verification-banner'
import { AnnouncementAlertBanner } from '@/components/citizen/dashboard/announcement-alert-banner'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { useNotifications } from '@/hooks/use-notifications'
import {
  countComplaintsByStatus,
  countRequestsByStatus,
  sortByCreatedAtDesc,
} from '@/lib/citizen-stats'
import { getOrCreateResidentProfile } from '@/lib/residents'
import { isAnnouncementColumnError } from '@/lib/announcements'
import { createClient } from '@/lib/supabase/client'
import type { SupabaseClient } from '@supabase/supabase-js'
import { Bell, FileWarning, Megaphone, Plus, ShieldCheck } from 'lucide-react'

/** Activity lists show at most this many of the newest rows. */
const RECENT_LIMIT = 3

// Explicit column lists instead of `select('*')`: the requests table stores a
// JSONB `payload` that can embed base64 attachments, which the dashboard has
// no use for (see `lib/request-types.ts` -> RequestFileValue).
const REQUEST_COLUMNS = 'id, title, category, status, created_at, request_type'
// Deployments that predate migration 04 have no request_type column; the card
// title falls back to `title` (see `getRequestTypeTitle`) when it is absent.
const REQUEST_COLUMNS_LEGACY = 'id, title, category, status, created_at'
const COMPLAINT_COLUMNS = 'id, title, category, status, created_at'
const ANNOUNCEMENT_COLUMNS_FULL = 'id, title, category, created_at, excerpt, published_at, expires_at, pinned'
const ANNOUNCEMENT_COLUMNS_NO_PIN = 'id, title, category, created_at, excerpt, published_at'
const ANNOUNCEMENT_COLUMNS_BASE = 'id, title, category, created_at, excerpt'

type ComplaintRow = RecentComplaint

type MessageRow = {
  id: string
  message: string
  created_at: string
  complaint_id: string
  complaints?: { title: string | null; status: string | null } | null
}

/**
 * Mirrors the identifier generated by migration 11
 * (`'RPT-' || UPPER(SUBSTRING(id::text, 1, 8))`) and the admin fallback in
 * `components/admin/resident-reports-page.tsx`, so a citizen can quote the
 * same number the barangay sees.
 */
function buildTrackingNumber(id: string) {
  return `RPT-${id.slice(0, 8).toUpperCase()}`
}

async function loadComplaints(
  supabase: SupabaseClient,
  residentId: string,
): Promise<ComplaintRow[]> {
  const { data, error } = await supabase
    .from('complaints')
    .select(`${COMPLAINT_COLUMNS}, tracking_number`)
    .eq('resident_id', residentId)
    .order('created_at', { ascending: false })

  if (!error) {
    return (data ?? []) as unknown as ComplaintRow[]
  }

  // Deployments that predate migration 11 have no tracking_number column;
  // derive it from the row id instead of failing the whole page.
  if (!/tracking_number/i.test(error.message ?? '')) {
    throw error
  }

  const fallback = await supabase
    .from('complaints')
    .select(COMPLAINT_COLUMNS)
    .eq('resident_id', residentId)
    .order('created_at', { ascending: false })

  if (fallback.error) {
    throw fallback.error
  }

  return ((fallback.data ?? []) as unknown as ComplaintRow[]).map((row) => ({
    ...row,
    tracking_number: buildTrackingNumber(row.id),
  }))
}

async function loadRequests(
  supabase: SupabaseClient,
  residentId: string,
): Promise<RecentRequest[]> {
  const { data, error } = await supabase
    .from('requests')
    .select(REQUEST_COLUMNS)
    .eq('resident_id', residentId)
    .order('created_at', { ascending: false })

  if (!error) {
    return (data ?? []) as unknown as RecentRequest[]
  }

  if (!/request_type/i.test(error.message ?? '')) {
    throw error
  }

  console.warn(
    'requests.request_type is missing, so request type titles cannot be shown. Apply scripts/04_add_request_payload.sql:',
    error.message,
  )

  const fallback = await supabase
    .from('requests')
    .select(REQUEST_COLUMNS_LEGACY)
    .eq('resident_id', residentId)
    .order('created_at', { ascending: false })

  if (fallback.error) {
    throw fallback.error
  }

  return ((fallback.data ?? []) as unknown as RecentRequest[]).map((row) => ({
    ...row,
    request_type: null,
  }))
}

async function loadUnreadReplies(
  supabase: SupabaseClient,
  userId: string,
): Promise<UnreadReply[]> {
  const { data, error } = await supabase
    .from('complaint_messages')
    .select('id, message, created_at, complaint_id, complaints(title, status)')
    .eq('recipient_user_id', userId)
    .eq('is_read', false)
    .order('created_at', { ascending: false })
    .limit(RECENT_LIMIT)

  if (error) {
    // Deployments that predate migration 02 have neither recipient_user_id nor
    // is_read (see scripts/02_add_geolocation.sql). The notifications page and
    // the notification badge already degrade to "nothing unread" in that case,
    // so do the same here instead of failing the entire dashboard.
    if (/recipient_user_id|is_read/i.test(error.message ?? '')) {
      console.warn(
        'complaint_messages.recipient_user_id/is_read is missing, so unread replies cannot be listed. Apply scripts/02_add_geolocation.sql:',
        error.message,
      )
      return []
    }

    throw error
  }

  return ((data ?? []) as unknown as MessageRow[]).map((row) => ({
    id: row.id,
    message: row.message,
    created_at: row.created_at,
    complaint_id: row.complaint_id,
    complaint_title: row.complaints?.title ?? null,
    complaint_status: row.complaints?.status ?? null,
  }))
}

/**
 * Announcements a resident should actually see: published, already live (a
 * future `published_at` is a schedule) and not expired. Visibility is resolved
 * at read time, so scheduling needs no background job.
 *
 * The extra query variants only exist so deployments still work before
 * migration 27 (pinned/expires_at) has been applied.
 */
async function loadVisibleAnnouncements(
  supabase: SupabaseClient,
  options: { limit: number; category?: string },
): Promise<DashboardAnnouncement[]> {
  const now = new Date().toISOString()
  const { limit, category } = options

  const start = (columns: string) => {
    const query = supabase.from('announcements').select(columns).eq('is_published', true)
    return category ? query.eq('category', category) : query
  }

  const attempts: Array<() => PromiseLike<{ data: any[] | null; error: any }>> = [
    () =>
      start(ANNOUNCEMENT_COLUMNS_FULL)
        .lte('published_at', now)
        .or(`expires_at.is.null,expires_at.gt.${now}`)
        .order('pinned', { ascending: false })
        .order('published_at', { ascending: false })
        .limit(limit),
    () =>
      start(ANNOUNCEMENT_COLUMNS_NO_PIN)
        .lte('published_at', now)
        .order('published_at', { ascending: false })
        .limit(limit),
    () =>
      start(ANNOUNCEMENT_COLUMNS_BASE)
        .order('created_at', { ascending: false })
        .limit(limit),
  ]

  let lastError: any = null

  for (const attempt of attempts) {
    const { data, error } = await attempt()

    if (!error) {
      return (data ?? []) as unknown as DashboardAnnouncement[]
    }

    lastError = error
    if (!isAnnouncementColumnError(error)) break
  }

  // A genuinely broken query should surface, but a database missing one of the
  // optional columns only means the cards show nothing.
  if (lastError && !isAnnouncementColumnError(lastError)) {
    throw lastError
  }

  console.warn(
    'announcements could not be read with the current schema, apply the announcements migrations:',
    lastError?.message,
  )
  return []
}

function describeError(error: unknown): string {
  if (error instanceof Error) return error.message
  if (error && typeof error === 'object' && 'message' in error) {
    return String((error as Record<string, unknown>).message)
  }
  return JSON.stringify(error)
}

export default function CitizenDashboard() {
  const [loading, setLoading] = useState(true)
  const [fetchError, setFetchError] = useState<string | null>(null)
  const [userName, setUserName] = useState<string>('Resident')
  const [verificationStatus, setVerificationStatus] = useState<string>('unverified')
  const [verificationConfidence, setVerificationConfidence] = useState<number | null>(null)
  const [requests, setRequests] = useState<RecentRequest[]>([])
  const [complaints, setComplaints] = useState<ComplaintRow[]>([])
  const [unreadReplies, setUnreadReplies] = useState<UnreadReply[]>([])
  const [announcements, setAnnouncements] = useState<DashboardAnnouncement[]>([])
  const [activeAlert, setActiveAlert] = useState<DashboardAnnouncement | null>(null)
  const { unreadCount, refreshUnreadCount } = useNotifications()

  useEffect(() => {
    let cancelled = false

    async function loadData() {
      try {
        const supabase = createClient()

        const {
          data: { user },
        } = await supabase.auth.getUser()

        if (!user) {
          return
        }

        if (!cancelled) {
          setUserName(
            user.user_metadata?.first_name || user.email?.split('@')[0] || 'Resident',
          )
        }

        const resident = await getOrCreateResidentProfile(supabase, user)
        if (!resident) {
          throw new Error('We could not load your resident profile. Please sign in again.')
        }

        if (!cancelled) {
          setVerificationStatus(resident.verification_status ?? 'unverified')
          setVerificationConfidence(resident.verification_confidence ?? null)
        }

        // These five reads are independent, so run them concurrently rather
        // than chaining round trips.
        const [requestRows, complaintRows, replies, latestAnnouncements, alertRows] =
          await Promise.all([
            loadRequests(supabase, resident.id),
            loadComplaints(supabase, resident.id),
            loadUnreadReplies(supabase, user.id),
            loadVisibleAnnouncements(supabase, { limit: RECENT_LIMIT }),
            loadVisibleAnnouncements(supabase, { limit: 1, category: 'Alert' }),
          ])

        if (cancelled) return

        // Rows arrive newest-first from the database; the cards slice what
        // they display while the stats helpers count every row.
        setRequests(sortByCreatedAtDesc(requestRows))
        setComplaints(sortByCreatedAtDesc(complaintRows))
        setUnreadReplies(replies)
        setAnnouncements(latestAnnouncements)
        setActiveAlert(alertRows[0] ?? null)

        await refreshUnreadCount()
      } catch (error: unknown) {
        console.error('Error loading dashboard data:', describeError(error), error)
        if (!cancelled) {
          setFetchError(describeError(error))
        }
      } finally {
        if (!cancelled) {
          setLoading(false)
        }
      }
    }

    loadData()

    return () => {
      cancelled = true
    }
  }, [refreshUnreadCount])

  const requestCounts = useMemo(() => countRequestsByStatus(requests), [requests])
  const complaintCounts = useMemo(() => countComplaintsByStatus(complaints), [complaints])
  const recentRequests = useMemo(() => requests.slice(0, RECENT_LIMIT), [requests])
  const recentComplaints = useMemo(() => complaints.slice(0, RECENT_LIMIT), [complaints])

  // A rejected ID submission makes re-verification the most important action,
  // so it takes the primary button slot from "New Service Request".
  const verificationRejected = verificationStatus === 'rejected'

  return (
    <div className="space-y-6 p-6 md:p-8">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold">Welcome back, {userName}! 👋</h1>
          <p className="mt-2 text-muted-foreground">
            Here&apos;s an overview of your civic activities
          </p>
        </div>
        <Link
          href="/citizen/notifications"
          aria-label={
            unreadCount > 0 ? `Notifications, ${unreadCount} unread` : 'Notifications'
          }
        >
          <Button variant="ghost" size="icon" className="relative">
            <Bell className="h-5 w-5" aria-hidden="true" />
            {unreadCount > 0 && (
              <span className="absolute -right-1 -top-1 flex h-5 w-5 items-center justify-center rounded-full bg-primary text-xs text-primary-foreground">
                {unreadCount}
              </span>
            )}
          </Button>
        </Link>
      </div>

      {/* Error Display */}
      {fetchError && (
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-red-700 dark:border-red-500/30 dark:bg-red-500/10 dark:text-red-300">
          <p className="font-semibold">Error loading dashboard:</p>
          <p className="text-sm">{fetchError}</p>
        </div>
      )}

      {/* Urgent barangay notice sits above everything else once acknowledged. */}
      <AnnouncementAlertBanner alert={activeAlert} loading={loading} />

      <VerificationBanner
        status={verificationStatus}
        confidence={verificationConfidence}
      />

      <UnreadRepliesCard replies={unreadReplies} loading={loading} />

      <StatsGrid loading={loading} requests={requestCounts} complaints={complaintCounts} />

      {/* Quick Actions */}
      <Card>
        <CardHeader>
          <CardTitle>Quick Actions</CardTitle>
          <CardDescription>
            Get started with a new service request or complaint
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-wrap gap-3">
          {verificationRejected ? (
            <Link href="/citizen/verify-id">
              <Button className="bg-primary hover:bg-primary/90">
                <ShieldCheck className="mr-2 h-4 w-4" aria-hidden="true" />
                Re-upload ID
              </Button>
            </Link>
          ) : (
            <Link href="/citizen/request-service">
              <Button className="bg-primary hover:bg-primary/90">
                <Plus className="mr-2 h-4 w-4" aria-hidden="true" />
                New Service Request
              </Button>
            </Link>
          )}
          <Link href="/citizen/file-complaint">
            <Button variant="outline">
              <FileWarning className="mr-2 h-4 w-4" aria-hidden="true" />
              File a Complaint
            </Button>
          </Link>
          <Link href="/citizen/announcements">
            <Button variant="outline">
              <Megaphone className="mr-2 h-4 w-4" aria-hidden="true" />
              View Announcements
            </Button>
          </Link>
        </CardContent>
      </Card>

      <div className="grid gap-6 lg:grid-cols-2">
        <RecentRequestsCard requests={recentRequests} loading={loading} />
        <RecentComplaintsCard complaints={recentComplaints} loading={loading} />
      </div>

      <AnnouncementsCard announcements={announcements} loading={loading} />
    </div>
  )
}
